-- AlterTable Company SSO
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "ssoEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "ssoLabel" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "ssoIssuer" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "ssoClientId" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "ssoClientSecret" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "ssoAutoApprove" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "ssoEmailDomains" TEXT[] DEFAULT ARRAY[]::TEXT[];
